### ISSUE TITLE
Assignment 2 issue

### ISSUE THREAD

**Issue by memphis88** [e-conomic/client-side-application-course#34]
I am almost done but for some obscure reason I get double span elements for each message submitted. I also noticed that when I insert the first message in the array, the component "ComponentBox" re-renders with every press of a key on the text-field.

Edit: It's double span elements as children of a single span element for every message submitted.

``` html
<span class="" data-reactid=".0.2.$0">
    <span data-reactid=".0.2.$0.0"></span>
    <span data-reactid=".0.2.$0.1">asdf</span><br data-reactid=".0.2.$0.2">
</span>
```

**Comment by calinilie** [comment]
It has to do with this bit of code

``` jsx
<span className={this.props.isError ? 'error' : ''}>
        {this.props.isError ? 'Error: ' : ''}{this.props.text}<br/>
</span>
```

This statement `{this.props.isError ? 'Error: ' : ''}` evalutates to a string. Then you have another statement which evaluates to a string: `{this.props.text}`. It seems like react treats them as individual components, so it wraps them in a span element and assigns a `data-reactid` in order to perform the diff on them.

If you change that line to: 

``` jsx
<span className={this.props.isError ? 'error' : ''} style={{display: 'block'}}>
        {(this.props.isError ? 'Error: ' : '') + this.props.text}
</span>
```

It won't render 2 spans.

Here is a stackoverflow question, answered by one FB developer who works on react. http://stackoverflow.com/questions/24469474/how-to-ouput-text-in-reactjs-without-wrapping-it-in-span

Perhaps @hulvei3 knows more about this?

**Comment by calinilie** [comment]
Link to pr: https://github.com/e-conomic/client-side-application-course/pull/36

**Comment by hulvei3** [comment]
:+1: nope
